apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev-
namespace: development
images:
- name: acraz01edu01.azurecr.io/edu00/myapp
  newTag: latest
- name: acraz01edu01.azurecr.io/neocode24/myapp
  newName: acraz01edu01.azurecr.io/neocode24/myapp
