apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- acr-secrets.yaml
namePrefix: dev-
namespace: development

patchesStrategicMerge:
- patches/deployment-patch.yaml

images:
- name: acraz01edu01.azurecr.io/edu00/myapp
  newName: acraz01edu01.azurecr.io/edu00/myapp
  newTag: latest
