apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: prod-
namespace: production

patchesStrategicMerge:
- patches/deployment-patch.yaml

images:
- name: acraz01edu01.azurecr.io/npm-hello-world
  newName: acraz01edu01.azurecr.io/npm-hello-world-main
- name: npm-hello-world
  newName: acraz01edu01.azurecr.io/npm-hello-world-main
  newTag: npm-hello-world.250704.1048.v010
